name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.10.0]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'

      - name: Build
        run: |
          npm install
          npm run build

      - name: Download basic.ics file
        run: curl -o dist/basic.ics https://calendar.google.com/calendar/ical/c_f1b5b03aab2eedcceb374183e0d44d60d87ccd43653dd79f91f12c16bb5a78fc%40group.calendar.google.com/public/basic.ics

      - name: Get events from Google API
        run: npm run get-events

      - name: Add CNAME in dist folder
        run: cp CNAME dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: dist
        if: github.event_name != 'pull_request'
